stan-core:
  stanPath: .stan
  excludes:
    - '*.local'
    - assets/**
    - CHANGELOG.md
    - docs/**
    - package-lock.json
  imports:
    entity-manager:
      - ../entity-manager/.stan/system/stan.requirements.md
      - ../entity-manager/.stan/system/stan.todo.md
      - ../entity-manager/dist/index.d.ts
      - ../entity-manager/.stan/interop/entity-client-dynamodb/**
stan-cli:
  cliDefaults:
    run:
      facets: true
      plan: false
      sequential: true
  patchOpenCommand: code -g {file}
  scripts:
    typecheck: npm run typecheck
    lint: npm run lint:fix
    test: npm run test -- --no-color
    build:
      script: cross-env NO_COLOR=1 npm run build
      warnPattern: '^\\(\\!\\)\\s(?!\\[plugin typescript\\]\\s@rollup/plugin-typescript: outputToFile[Ss]ystem option is defaulting to true\\b).+'
    docs:
      script: npm run docs -- --emit none
      warnPattern: \\[warning\\]
    knip: npm run knip

